#!/bin/bash
# Startonce wrapper script for xflux

# Include the needed delicate scripts
. $( dirname ${BASH_SOURCE[0]} )/delicate/location || exit 1;

# Include the header script
. $( dirname ${BASH_SOURCE[0]} )/header || exit 1;

# Start xflux
# Not using wrap function: -nofork bugged...
/usr/bin/xflux -l $latitude -g $longitude;

# Work around.
pid=$( pgrep 'xflux'; );
result=$?;
echo $pid | tee $PID_FILE;

while [ $result -eq '0' ]; do
  sleep 1;
  pgrep 'xflux';
  result=$?;
done;
